### ISSUE TITLE
Data from array

### ISSUE THREAD

**Issue by sayonaralive** [xfrocks/bdApi_Android#1]
hello. how turn off array data to normal using?

**Comment by daohoangson** [comment]
Hi @sayonaralive, sorry I don't understand your question. Can you describe it in more details?

**Comment by sayonaralive** [comment]
If i open application - opened array details and i need open array object -> links -> details for view thread, but need open thread not use array

**Comment by ghost** [comment]
Ah, this application is built as a demo so it do things differently from an
end user stand point. You will need a developer to develop your own app for
your site.

**Comment by sayonaralive** [comment]
okay :c thank you
> 29 сент. 2017 г., в 10:28, xfrocks-dev <notifications@github.com> написал(а):
> 
> Ah, this application is built as a demo so it do things differently from an
> end user stand point. You will need a developer to develop your own app for
> your site.
> 
>
